using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("DEV")]
[assembly: AssemblyCompanyAttribute("http://www.KeyToneTech.com")]
[assembly: AssemblyProductAttribute("TAXONPLATFORM")]
[assembly: AssemblyCopyrightAttribute("@Keytone Technologies 2010")]
[assembly: AssemblyTrademarkAttribute("KeyTone Technologies, RFIDSDK")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("4.0.*")]
[assembly: AssemblyInformationalVersionAttribute("4.0.0")]

