using OfficeOpenXml;
using OfficeOpenXml.Style;
using RichTextBoxPrintCtrl;
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Drawing.Printing;
using System.IO;
using System.Windows.Forms;

namespace DealStore
{
    partial class frmPallets
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.richTextBoxPrintCtrl1 = new RichTextBoxPrintCtrl.RichTextBoxPrintCtrl();
            this.label1 = new Label();
            this.btnMainMenu = new Button();
            this.groupBox2 = new GroupBox();
            this.gbPalletDetails = new GroupBox();
            this.lblPalletLocation = new Label();
            this.label12 = new Label();
            this.btnGenerateReport = new Button();
            this.lblTotalPriceLabel = new Label();
            this.lblTotalPriceActual = new Label();
            this.lblTotalItems = new Label();
            this.label10 = new Label();
            this.label8 = new Label();
            this.label6 = new Label();
            this.lblPalletID = new Label();
            this.btnGenerateBarcode = new Button();
            this.lblPallet = new Label();
            this.label9 = new Label();
            this.lblLoadName = new Label();
            this.label7 = new Label();
            this.lblVendorName = new Label();
            this.btnClose = new Button();
            this.btnDeletePalletItem = new Button();
            this.gvPalletProducts = new DataGridView();
            this.label3 = new Label();
            this.label11 = new Label();
            this.txtPalletLocation = new TextBox();
            this.btnDetails = new Button();
            this.ddlVendorLoad = new ComboBox();
            this.ddlVendors = new ComboBox();
            this.label4 = new Label();
            this.txtPallet = new TextBox();
            this.label2 = new Label();
            this.btnDelete = new Button();
            this.gvPallets = new DataGridView();
            this.btnAdd = new Button();
            this.label5 = new Label();
            this.printDocument1 = new PrintDocument();
            this.groupBox2.SuspendLayout();
            this.gbPalletDetails.SuspendLayout();
            ((ISupportInitialize)this.gvPalletProducts).BeginInit();
            ((ISupportInitialize)this.gvPallets).BeginInit();
            base.SuspendLayout();
            this.richTextBoxPrintCtrl1.Location = new Point(0x2e2, 0x1ad);
            this.richTextBoxPrintCtrl1.Name = "richTextBoxPrintCtrl1";
            this.richTextBoxPrintCtrl1.Size = new Size(0x11, 20);
            this.richTextBoxPrintCtrl1.TabIndex = 0x1f;
            this.richTextBoxPrintCtrl1.Text = "";
            this.richTextBoxPrintCtrl1.Visible = false;
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Verdana", 12f, FontStyle.Underline, GraphicsUnit.Point, 0);
            this.label1.ForeColor = SystemColors.HighlightText;
            this.label1.Location = new Point(0x12a, 9);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x4d, 0x12);
            this.label1.TabIndex = 11;
            this.label1.Text = "PALLETS";
            this.btnMainMenu.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnMainMenu.Location = new Point(0x217, 0x1ff);
            this.btnMainMenu.Name = "btnMainMenu";
            this.btnMainMenu.Size = new Size(0x81, 0x17);
            this.btnMainMenu.TabIndex = 0x15;
            this.btnMainMenu.Text = "Main Menu";
            this.btnMainMenu.UseVisualStyleBackColor = true;
            this.btnMainMenu.Click += new EventHandler(this.btnMainMenu_Click);
            this.groupBox2.BackColor = SystemColors.ActiveBorder;
            this.groupBox2.Controls.Add(this.gbPalletDetails);
            this.groupBox2.Controls.Add(this.label11);
            this.groupBox2.Controls.Add(this.txtPalletLocation);
            this.groupBox2.Controls.Add(this.btnDetails);
            this.groupBox2.Controls.Add(this.ddlVendorLoad);
            this.groupBox2.Controls.Add(this.ddlVendors);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.txtPallet);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.btnDelete);
            this.groupBox2.Controls.Add(this.gvPallets);
            this.groupBox2.Controls.Add(this.btnAdd);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.richTextBoxPrintCtrl1);
            this.groupBox2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox2.Location = new Point(12, 40);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0x28c, 0x1d1);
            this.groupBox2.TabIndex = 0x16;
            this.groupBox2.TabStop = false;
            this.gbPalletDetails.BackColor = SystemColors.ActiveBorder;
            this.gbPalletDetails.Controls.Add(this.lblPalletLocation);
            this.gbPalletDetails.Controls.Add(this.label12);
            this.gbPalletDetails.Controls.Add(this.btnGenerateReport);
            this.gbPalletDetails.Controls.Add(this.lblTotalPriceLabel);
            this.gbPalletDetails.Controls.Add(this.lblTotalPriceActual);
            this.gbPalletDetails.Controls.Add(this.lblTotalItems);
            this.gbPalletDetails.Controls.Add(this.label10);
            this.gbPalletDetails.Controls.Add(this.label8);
            this.gbPalletDetails.Controls.Add(this.label6);
            this.gbPalletDetails.Controls.Add(this.lblPalletID);
            this.gbPalletDetails.Controls.Add(this.btnGenerateBarcode);
            this.gbPalletDetails.Controls.Add(this.lblPallet);
            this.gbPalletDetails.Controls.Add(this.label9);
            this.gbPalletDetails.Controls.Add(this.lblLoadName);
            this.gbPalletDetails.Controls.Add(this.label7);
            this.gbPalletDetails.Controls.Add(this.lblVendorName);
            this.gbPalletDetails.Controls.Add(this.btnClose);
            this.gbPalletDetails.Controls.Add(this.btnDeletePalletItem);
            this.gbPalletDetails.Controls.Add(this.gvPalletProducts);
            this.gbPalletDetails.Controls.Add(this.label3);
            this.gbPalletDetails.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.gbPalletDetails.Location = new Point(0, 0);
            this.gbPalletDetails.Name = "gbPalletDetails";
            this.gbPalletDetails.Size = new Size(0x28c, 0x1d1);
            this.gbPalletDetails.TabIndex = 7;
            this.gbPalletDetails.TabStop = false;
            this.gbPalletDetails.Visible = false;
            this.lblPalletLocation.AutoSize = true;
            this.lblPalletLocation.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblPalletLocation.Location = new Point(0x60, 0x69);
            this.lblPalletLocation.Name = "lblPalletLocation";
            this.lblPalletLocation.Size = new Size(0, 13);
            this.lblPalletLocation.TabIndex = 20;
            this.label12.AutoSize = true;
            this.label12.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label12.Location = new Point(7, 0x69);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x42, 13);
            this.label12.TabIndex = 0x13;
            this.label12.Text = "Location:";
            this.btnGenerateReport.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnGenerateReport.Location = new Point(0x1fa, 0x79);
            this.btnGenerateReport.Name = "btnGenerateReport";
            this.btnGenerateReport.Size = new Size(140, 0x17);
            this.btnGenerateReport.TabIndex = 0x12;
            this.btnGenerateReport.Text = "Generate Report";
            this.btnGenerateReport.UseVisualStyleBackColor = true;
            this.btnGenerateReport.Click += new EventHandler(this.btnGenerateReport_Click);
            this.lblTotalPriceLabel.AutoSize = true;
            this.lblTotalPriceLabel.Font = new Font("Verdana", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblTotalPriceLabel.Location = new Point(520, 0x199);
            this.lblTotalPriceLabel.Name = "lblTotalPriceLabel";
            this.lblTotalPriceLabel.Size = new Size(0, 14);
            this.lblTotalPriceLabel.TabIndex = 0x11;
            this.lblTotalPriceActual.AutoSize = true;
            this.lblTotalPriceActual.Font = new Font("Verdana", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblTotalPriceActual.Location = new Point(0x11e, 0x199);
            this.lblTotalPriceActual.Name = "lblTotalPriceActual";
            this.lblTotalPriceActual.Size = new Size(0, 14);
            this.lblTotalPriceActual.TabIndex = 0x10;
            this.lblTotalItems.AutoSize = true;
            this.lblTotalItems.Font = new Font("Verdana", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblTotalItems.Location = new Point(0x60, 0x199);
            this.lblTotalItems.Name = "lblTotalItems";
            this.lblTotalItems.Size = new Size(0, 14);
            this.lblTotalItems.TabIndex = 15;
            this.label10.AutoSize = true;
            this.label10.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label10.Location = new Point(0x189, 0x199);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x80, 13);
            this.label10.TabIndex = 14;
            this.label10.Text = "Total Price(Label):";
            this.label8.AutoSize = true;
            this.label8.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label8.Location = new Point(150, 0x199);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x86, 13);
            this.label8.TabIndex = 13;
            this.label8.Text = "Total Price(Actual):";
            this.label6.AutoSize = true;
            this.label6.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label6.Location = new Point(7, 0x199);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x56, 13);
            this.label6.TabIndex = 12;
            this.label6.Text = "Total Items:";
            this.lblPalletID.AutoSize = true;
            this.lblPalletID.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblPalletID.Location = new Point(0x275, 0x5b);
            this.lblPalletID.Name = "lblPalletID";
            this.lblPalletID.Size = new Size(0, 13);
            this.lblPalletID.TabIndex = 11;
            this.lblPalletID.Visible = false;
            this.btnGenerateBarcode.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnGenerateBarcode.Location = new Point(0x157, 0x79);
            this.btnGenerateBarcode.Name = "btnGenerateBarcode";
            this.btnGenerateBarcode.Size = new Size(0x9d, 0x17);
            this.btnGenerateBarcode.TabIndex = 10;
            this.btnGenerateBarcode.Text = "Generate Barcode";
            this.btnGenerateBarcode.UseVisualStyleBackColor = true;
            this.btnGenerateBarcode.Click += new EventHandler(this.btnGenerateBarcode_Click);
            this.lblPallet.AutoSize = true;
            this.lblPallet.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblPallet.Location = new Point(0x60, 0x4f);
            this.lblPallet.Name = "lblPallet";
            this.lblPallet.Size = new Size(0, 13);
            this.lblPallet.TabIndex = 9;
            this.label9.AutoSize = true;
            this.label9.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label9.Location = new Point(6, 80);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x30, 13);
            this.label9.TabIndex = 8;
            this.label9.Text = "Pallet:";
            this.lblLoadName.AutoSize = true;
            this.lblLoadName.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblLoadName.Location = new Point(0x60, 0x36);
            this.lblLoadName.Name = "lblLoadName";
            this.lblLoadName.Size = new Size(0, 13);
            this.lblLoadName.TabIndex = 7;
            this.label7.AutoSize = true;
            this.label7.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label7.Location = new Point(7, 0x37);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x2a, 13);
            this.label7.TabIndex = 6;
            this.label7.Text = "Load:";
            this.lblVendorName.AutoSize = true;
            this.lblVendorName.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblVendorName.Location = new Point(0x60, 0x1d);
            this.lblVendorName.Name = "lblVendorName";
            this.lblVendorName.Size = new Size(0, 13);
            this.lblVendorName.TabIndex = 5;
            this.btnClose.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnClose.Location = new Point(0x22f, 0x1b4);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new Size(0x57, 0x17);
            this.btnClose.TabIndex = 4;
            this.btnClose.Text = "Close";
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnClose.Click += new EventHandler(this.btnClose_Click);
            this.btnDeletePalletItem.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnDeletePalletItem.Location = new Point(6, 0x79);
            this.btnDeletePalletItem.Name = "btnDeletePalletItem";
            this.btnDeletePalletItem.Size = new Size(0x57, 0x17);
            this.btnDeletePalletItem.TabIndex = 2;
            this.btnDeletePalletItem.Text = "Delete";
            this.btnDeletePalletItem.UseVisualStyleBackColor = true;
            this.btnDeletePalletItem.Click += new EventHandler(this.btnDeletePalletItem_Click);
            this.gvPalletProducts.AllowUserToAddRows = false;
            this.gvPalletProducts.AllowUserToDeleteRows = false;
            this.gvPalletProducts.AllowUserToOrderColumns = true;
            this.gvPalletProducts.AllowUserToResizeColumns = false;
            this.gvPalletProducts.AllowUserToResizeRows = false;
            this.gvPalletProducts.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gvPalletProducts.Location = new Point(6, 150);
            this.gvPalletProducts.MultiSelect = false;
            this.gvPalletProducts.Name = "gvPalletProducts";
            this.gvPalletProducts.ReadOnly = true;
            this.gvPalletProducts.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.gvPalletProducts.Size = new Size(640, 0x100);
            this.gvPalletProducts.TabIndex = 3;
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label3.Location = new Point(7, 30);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x39, 13);
            this.label3.TabIndex = 1;
            this.label3.Text = "Vendor:";
            this.label11.AutoSize = true;
            this.label11.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label11.Location = new Point(6, 110);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x42, 13);
            this.label11.TabIndex = 0x21;
            this.label11.Text = "Location:";
            this.txtPalletLocation.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.txtPalletLocation.Location = new Point(0x89, 0x6b);
            this.txtPalletLocation.MaxLength = 100;
            this.txtPalletLocation.Name = "txtPalletLocation";
            this.txtPalletLocation.Size = new Size(0x111, 0x15);
            this.txtPalletLocation.TabIndex = 3;
            this.btnDetails.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnDetails.Location = new Point(0x1b3, 140);
            this.btnDetails.Name = "btnDetails";
            this.btnDetails.Size = new Size(0x76, 0x17);
            this.btnDetails.TabIndex = 5;
            this.btnDetails.Text = "View Details";
            this.btnDetails.UseVisualStyleBackColor = true;
            this.btnDetails.Click += new EventHandler(this.btnDetails_Click);
            this.ddlVendorLoad.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ddlVendorLoad.FormattingEnabled = true;
            this.ddlVendorLoad.Location = new Point(0x89, 0x35);
            this.ddlVendorLoad.Name = "ddlVendorLoad";
            this.ddlVendorLoad.Size = new Size(0x111, 0x15);
            this.ddlVendorLoad.TabIndex = 1;
            this.ddlVendors.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ddlVendors.FormattingEnabled = true;
            this.ddlVendors.Location = new Point(0x89, 0x1a);
            this.ddlVendors.Name = "ddlVendors";
            this.ddlVendors.Size = new Size(0x111, 0x15);
            this.ddlVendors.TabIndex = 0;
            this.ddlVendors.SelectedIndexChanged += new EventHandler(this.ddlVendors_SelectedIndexChanged);
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label4.Location = new Point(6, 0x1d);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x39, 13);
            this.label4.TabIndex = 0x10;
            this.label4.Text = "Vendor:";
            this.txtPallet.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.txtPallet.Location = new Point(0x89, 80);
            this.txtPallet.MaxLength = 100;
            this.txtPallet.Name = "txtPallet";
            this.txtPallet.Size = new Size(0x111, 0x15);
            this.txtPallet.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label2.Location = new Point(6, 0x53);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x30, 13);
            this.label2.TabIndex = 7;
            this.label2.Text = "Pallet:";
            this.btnDelete.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnDelete.Location = new Point(0x22f, 140);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new Size(0x57, 0x17);
            this.btnDelete.TabIndex = 6;
            this.btnDelete.Text = "Delete";
            this.btnDelete.UseVisualStyleBackColor = true;
            this.btnDelete.Click += new EventHandler(this.btnDelete_Click);
            this.gvPallets.AllowUserToAddRows = false;
            this.gvPallets.AllowUserToDeleteRows = false;
            this.gvPallets.AllowUserToOrderColumns = true;
            this.gvPallets.AllowUserToResizeColumns = false;
            this.gvPallets.AllowUserToResizeRows = false;
            this.gvPallets.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gvPallets.Location = new Point(6, 0xa9);
            this.gvPallets.MultiSelect = false;
            this.gvPallets.Name = "gvPallets";
            this.gvPallets.ReadOnly = true;
            this.gvPallets.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.gvPallets.Size = new Size(640, 290);
            this.gvPallets.TabIndex = 7;
            this.btnAdd.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnAdd.Location = new Point(0x89, 140);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new Size(0x57, 0x17);
            this.btnAdd.TabIndex = 4;
            this.btnAdd.Text = "Add";
            this.btnAdd.UseVisualStyleBackColor = true;
            this.btnAdd.Click += new EventHandler(this.btnAdd_Click);
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label5.Location = new Point(6, 0x38);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x2a, 13);
            this.label5.TabIndex = 1;
            this.label5.Text = "Load:";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.DarkBlue;
            base.ClientSize = new Size(0x30b, 0x21d);
            base.ControlBox = false;
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.btnMainMenu);
            base.Controls.Add(this.label1);
            base.Name = "frmPallets";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Manage Pallets";
            base.WindowState = FormWindowState.Maximized;
            base.Load += new EventHandler(this.frmPallets_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.gbPalletDetails.ResumeLayout(false);
            this.gbPalletDetails.PerformLayout();
            ((ISupportInitialize)this.gvPalletProducts).EndInit();
            ((ISupportInitialize)this.gvPallets).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        #endregion
    }
}