using System;
using System.Drawing;
using System.Windows.Forms;

namespace DealStore
{
    partial class ImportForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Text = "ImportForm";

            this.groupBox2 = new GroupBox();
            this.ddlImportVendorLoad = new ComboBox();
            this.label10 = new Label();
            this.ddlImportVendors = new ComboBox();
            this.dpImportDate = new DateTimePicker();
            this.label9 = new Label();
            this.label8 = new Label();
            this.btnImport = new Button();
            this.txtExcelFile = new TextBox();
            this.btnBrowse = new Button();
            this.label5 = new Label();
            this.label1 = new Label();
            this.label2 = new Label();
            this.btnExportData = new Button();
            this.groupBox1 = new GroupBox();
            this.btnExportLabelData = new Button();
            this.label3 = new Label();
            this.groupBox3 = new GroupBox();
            this.cbAllVendors = new CheckBox();
            this.button1 = new Button();
            this.ddlLoadLoadReport = new ComboBox();
            this.label12 = new Label();
            this.ddlVendorLoadReport = new ComboBox();
            this.label11 = new Label();
            this.btnUserVendorSummaryReport = new Button();
            this.btnGenerateReport = new Button();
            this.ddlVendors = new ComboBox();
            this.label7 = new Label();
            this.dpEndDate = new DateTimePicker();
            this.label6 = new Label();
            this.dpStartDate = new DateTimePicker();
            this.label4 = new Label();
            this.btnMainMenu = new Button();
            this.label13 = new Label();
            this.groupBox4 = new GroupBox();
            this.dpEPEndDate = new DateTimePicker();
            this.dpEPStartDate = new DateTimePicker();
            this.label14 = new Label();
            this.label15 = new Label();
            this.btnEPReport = new Button();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            base.SuspendLayout();
            this.groupBox2.BackColor = SystemColors.ActiveBorder;
            this.groupBox2.Controls.Add(this.ddlImportVendorLoad);
            this.groupBox2.Controls.Add(this.label10);
            this.groupBox2.Controls.Add(this.ddlImportVendors);
            this.groupBox2.Controls.Add(this.dpImportDate);
            this.groupBox2.Controls.Add(this.label9);
            this.groupBox2.Controls.Add(this.label8);
            this.groupBox2.Controls.Add(this.btnImport);
            this.groupBox2.Controls.Add(this.txtExcelFile);
            this.groupBox2.Controls.Add(this.btnBrowse);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox2.Location = new Point(6, 0x1c);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0x2fe, 0x83);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.ddlImportVendorLoad.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ddlImportVendorLoad.FormattingEnabled = true;
            this.ddlImportVendorLoad.Items.AddRange(new object[] { "Yes", "No" });
            this.ddlImportVendorLoad.Location = new Point(0x18b, 13);
            this.ddlImportVendorLoad.Name = "ddlImportVendorLoad";
            this.ddlImportVendorLoad.Size = new Size(260, 0x15);
            this.ddlImportVendorLoad.TabIndex = 1;
            this.label10.AutoSize = true;
            this.label10.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label10.Location = new Point(0x14c, 0x10);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x2a, 13);
            this.label10.TabIndex = 0x20;
            this.label10.Text = "Load:";
            this.ddlImportVendors.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ddlImportVendors.FormattingEnabled = true;
            this.ddlImportVendors.Items.AddRange(new object[] { "Yes", "No" });
            this.ddlImportVendors.Location = new Point(70, 13);
            this.ddlImportVendors.Name = "ddlImportVendors";
            this.ddlImportVendors.Size = new Size(0xfd, 0x15);
            this.ddlImportVendors.TabIndex = 0;
            this.ddlImportVendors.SelectedIndexChanged += new EventHandler(this.ddlImportVendors_SelectedIndexChanged);
            this.dpImportDate.Format = DateTimePickerFormat.Short;
            this.dpImportDate.Location = new Point(70, 0x26);
            this.dpImportDate.Name = "dpImportDate";
            this.dpImportDate.Size = new Size(0xfd, 20);
            this.dpImportDate.TabIndex = 2;
            this.label9.AutoSize = true;
            this.label9.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label9.Location = new Point(7, 0x2c);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x29, 13);
            this.label9.TabIndex = 5;
            this.label9.Text = "Date:";
            this.label8.AutoSize = true;
            this.label8.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label8.Location = new Point(7, 0x10);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x39, 13);
            this.label8.TabIndex = 3;
            this.label8.Text = "Vendor:";
            this.btnImport.Font = new Font("Verdana", 10f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnImport.Location = new Point(70, 0x5b);
            this.btnImport.Name = "btnImport";
            this.btnImport.Size = new Size(0xfd, 0x21);
            this.btnImport.TabIndex = 4;
            this.btnImport.Text = "Import Data";
            this.btnImport.UseVisualStyleBackColor = true;
            this.btnImport.Click += new EventHandler(this.btnImport_Click);
            this.txtExcelFile.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.txtExcelFile.Location = new Point(70, 0x40);
            this.txtExcelFile.Name = "txtExcelFile";
            this.txtExcelFile.ReadOnly = true;
            this.txtExcelFile.Size = new Size(0x249, 0x15);
            this.txtExcelFile.TabIndex = 2;
            this.btnBrowse.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnBrowse.Location = new Point(0x295, 0x3e);
            this.btnBrowse.Name = "btnBrowse";
            this.btnBrowse.Size = new Size(0x61, 0x17);
            this.btnBrowse.TabIndex = 3;
            this.btnBrowse.Text = "Browse";
            this.btnBrowse.UseVisualStyleBackColor = true;
            this.btnBrowse.Click += new EventHandler(this.btnBrowse_Click);
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label5.Location = new Point(7, 0x43);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x23, 13);
            this.label5.TabIndex = 1;
            this.label5.Text = "File:";
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Verdana", 12f, FontStyle.Underline, GraphicsUnit.Point, 0);
            this.label1.ForeColor = SystemColors.HighlightText;
            this.label1.Location = new Point(0x147, 6);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x7a, 0x12);
            this.label1.TabIndex = 3;
            this.label1.Text = "IMPORT DATA";
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Verdana", 12f, FontStyle.Underline, GraphicsUnit.Point, 0);
            this.label2.ForeColor = SystemColors.HighlightText;
            this.label2.Location = new Point(0x149, 0xa4);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x7b, 0x12);
            this.label2.TabIndex = 4;
            this.label2.Text = "EXPORT DATA";
            this.btnExportData.Font = new Font("Verdana", 10f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnExportData.Location = new Point(10, 14);
            this.btnExportData.Name = "btnExportData";
            this.btnExportData.Size = new Size(0x139, 0x21);
            this.btnExportData.TabIndex = 0;
            this.btnExportData.Text = "Export All Data";
            this.btnExportData.UseVisualStyleBackColor = true;
            this.btnExportData.Click += new EventHandler(this.btnExportData_Click);
            this.groupBox1.BackColor = SystemColors.ActiveBorder;
            this.groupBox1.Controls.Add(this.btnExportLabelData);
            this.groupBox1.Controls.Add(this.btnExportData);
            this.groupBox1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox1.Location = new Point(6, 0xba);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x2fe, 0x38);
            this.groupBox1.TabIndex = 5;
            this.groupBox1.TabStop = false;
            this.btnExportLabelData.Font = new Font("Verdana", 10f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnExportLabelData.Location = new Point(0x1b9, 14);
            this.btnExportLabelData.Name = "btnExportLabelData";
            this.btnExportLabelData.Size = new Size(0x139, 0x21);
            this.btnExportLabelData.TabIndex = 1;
            this.btnExportLabelData.Text = "Export Labeled Data";
            this.btnExportLabelData.UseVisualStyleBackColor = true;
            this.btnExportLabelData.Click += new EventHandler(this.btnExportLabelData_Click);
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Verdana", 12f, FontStyle.Underline, GraphicsUnit.Point, 0);
            this.label3.ForeColor = SystemColors.HighlightText;
            this.label3.Location = new Point(0x15b, 0xf8);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x49, 0x12);
            this.label3.TabIndex = 6;
            this.label3.Text = "REPORT";
            this.groupBox3.BackColor = SystemColors.ActiveBorder;
            this.groupBox3.Controls.Add(this.cbAllVendors);
            this.groupBox3.Controls.Add(this.button1);
            this.groupBox3.Controls.Add(this.ddlLoadLoadReport);
            this.groupBox3.Controls.Add(this.label12);
            this.groupBox3.Controls.Add(this.ddlVendorLoadReport);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.btnUserVendorSummaryReport);
            this.groupBox3.Controls.Add(this.btnGenerateReport);
            this.groupBox3.Controls.Add(this.ddlVendors);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.dpEndDate);
            this.groupBox3.Controls.Add(this.label6);
            this.groupBox3.Controls.Add(this.dpStartDate);
            this.groupBox3.Controls.Add(this.label4);
            this.groupBox3.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox3.Location = new Point(6, 270);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x2fe, 0x6f);
            this.groupBox3.TabIndex = 6;
            this.groupBox3.TabStop = false;
            this.cbAllVendors.AutoSize = true;
            this.cbAllVendors.Location = new Point(0x171, 15);
            this.cbAllVendors.Name = "cbAllVendors";
            this.cbAllVendors.Size = new Size(90, 0x11);
            this.cbAllVendors.TabIndex = 0x23;
            this.cbAllVendors.Text = "All Vendors";
            this.cbAllVendors.UseVisualStyleBackColor = true;
            this.cbAllVendors.CheckedChanged += new EventHandler(this.cbAllVendors_CheckedChanged);
            this.button1.Font = new Font("Verdana", 8f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.button1.Location = new Point(0x24d, 70);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0xa9, 0x21);
            this.button1.TabIndex = 7;
            this.button1.Text = "Generate Load Report";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.ddlLoadLoadReport.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ddlLoadLoadReport.FormattingEnabled = true;
            this.ddlLoadLoadReport.Items.AddRange(new object[] { "Yes", "No" });
            this.ddlLoadLoadReport.Location = new Point(0x24d, 0x2b);
            this.ddlLoadLoadReport.Name = "ddlLoadLoadReport";
            this.ddlLoadLoadReport.Size = new Size(0xa9, 0x15);
            this.ddlLoadLoadReport.TabIndex = 6;
            this.label12.AutoSize = true;
            this.label12.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label12.Location = new Point(0x20e, 0x2e);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x2a, 13);
            this.label12.TabIndex = 0x22;
            this.label12.Text = "Load:";
            this.ddlVendorLoadReport.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ddlVendorLoadReport.FormattingEnabled = true;
            this.ddlVendorLoadReport.Items.AddRange(new object[] { "Yes", "No" });
            this.ddlVendorLoadReport.Location = new Point(0x24d, 13);
            this.ddlVendorLoadReport.Name = "ddlVendorLoadReport";
            this.ddlVendorLoadReport.Size = new Size(0xa9, 0x15);
            this.ddlVendorLoadReport.TabIndex = 5;
            this.ddlVendorLoadReport.SelectedIndexChanged += new EventHandler(this.ddlVendorLoadReport_SelectedIndexChanged);
            this.label11.AutoSize = true;
            this.label11.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label11.Location = new Point(0x20e, 0x10);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x39, 13);
            this.label11.TabIndex = 0x20;
            this.label11.Text = "Vendor:";
            this.btnUserVendorSummaryReport.Font = new Font("Verdana", 8f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnUserVendorSummaryReport.Location = new Point(0xdb, 0x42);
            this.btnUserVendorSummaryReport.Name = "btnUserVendorSummaryReport";
            this.btnUserVendorSummaryReport.Size = new Size(240, 0x21);
            this.btnUserVendorSummaryReport.TabIndex = 4;
            this.btnUserVendorSummaryReport.Text = "User && Vendor Summary Report";
            this.btnUserVendorSummaryReport.UseVisualStyleBackColor = true;
            this.btnUserVendorSummaryReport.Click += new EventHandler(this.btnUserVendorSummaryReport_Click);
            this.btnGenerateReport.Font = new Font("Verdana", 8f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnGenerateReport.Location = new Point(90, 0x42);
            this.btnGenerateReport.Name = "btnGenerateReport";
            this.btnGenerateReport.Size = new Size(0x7b, 0x21);
            this.btnGenerateReport.TabIndex = 3;
            this.btnGenerateReport.Text = "Generate Report";
            this.btnGenerateReport.UseVisualStyleBackColor = true;
            this.btnGenerateReport.Click += new EventHandler(this.btnGenerateReport_Click);
            this.ddlVendors.DropDownStyle = ComboBoxStyle.DropDownList;
            this.ddlVendors.FormattingEnabled = true;
            this.ddlVendors.Location = new Point(90, 13);
            this.ddlVendors.Name = "ddlVendors";
            this.ddlVendors.Size = new Size(0x111, 0x15);
            this.ddlVendors.TabIndex = 0;
            this.label7.AutoSize = true;
            this.label7.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label7.Location = new Point(7, 0x10);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x39, 13);
            this.label7.TabIndex = 6;
            this.label7.Text = "Vendor:";
            this.dpEndDate.Format = DateTimePickerFormat.Short;
            this.dpEndDate.Location = new Point(90, 40);
            this.dpEndDate.Name = "dpEndDate";
            this.dpEndDate.ShowCheckBox = true;
            this.dpEndDate.Size = new Size(0x8d, 20);
            this.dpEndDate.TabIndex = 1;
            this.label6.AutoSize = true;
            this.label6.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label6.Location = new Point(7, 0x2e);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x45, 13);
            this.label6.TabIndex = 4;
            this.label6.Text = "End Date:";
            this.dpStartDate.Format = DateTimePickerFormat.Short;
            this.dpStartDate.Location = new Point(0x13c, 40);
            this.dpStartDate.Name = "dpStartDate";
            this.dpStartDate.ShowCheckBox = true;
            this.dpStartDate.Size = new Size(0x8f, 20);
            this.dpStartDate.TabIndex = 2;
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label4.Location = new Point(0xe9, 0x2e);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x4d, 13);
            this.label4.TabIndex = 2;
            this.label4.Text = "Start Date:";
            this.btnMainMenu.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnMainMenu.Location = new Point(0x283, 0x205);
            this.btnMainMenu.Name = "btnMainMenu";
            this.btnMainMenu.Size = new Size(0x81, 0x17);
            this.btnMainMenu.TabIndex = 0x13;
            this.btnMainMenu.Text = "Main Menu";
            this.btnMainMenu.UseVisualStyleBackColor = true;
            this.btnMainMenu.Click += new EventHandler(this.btnMainMenu_Click);
            this.label13.AutoSize = true;
            this.label13.Font = new Font("Verdana", 12f, FontStyle.Underline, GraphicsUnit.Point, 0);
            this.label13.ForeColor = SystemColors.HighlightText;
            this.label13.Location = new Point(0xf3, 0x182);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x124, 0x12);
            this.label13.TabIndex = 20;
            this.label13.Text = "EMPLOYEE PERFORMANCE REPORT";
            this.groupBox4.BackColor = SystemColors.ActiveBorder;
            this.groupBox4.Controls.Add(this.btnEPReport);
            this.groupBox4.Controls.Add(this.dpEPEndDate);
            this.groupBox4.Controls.Add(this.dpEPStartDate);
            this.groupBox4.Controls.Add(this.label14);
            this.groupBox4.Controls.Add(this.label15);
            this.groupBox4.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox4.Location = new Point(6, 0x198);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(0x2fe, 0x5b);
            this.groupBox4.TabIndex = 0x15;
            this.groupBox4.TabStop = false;
            this.dpEPEndDate.Format = DateTimePickerFormat.Short;
            this.dpEPEndDate.Location = new Point(0x13c, 9);
            this.dpEPEndDate.Name = "dpEPEndDate";
            this.dpEPEndDate.ShowCheckBox = true;
            this.dpEPEndDate.Size = new Size(0x8f, 20);
            this.dpEPEndDate.TabIndex = 0x25;
            this.dpEPStartDate.Format = DateTimePickerFormat.Short;
            this.dpEPStartDate.Location = new Point(90, 10);
            this.dpEPStartDate.Name = "dpEPStartDate";
            this.dpEPStartDate.ShowCheckBox = true;
            this.dpEPStartDate.Size = new Size(0x8d, 20);
            this.dpEPStartDate.TabIndex = 0x24;
            this.label14.AutoSize = true;
            this.label14.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label14.Location = new Point(0xe9, 0x10);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x45, 13);
            this.label14.TabIndex = 6;
            this.label14.Text = "End Date:";
            this.label15.AutoSize = true;
            this.label15.Font = new Font("Verdana", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label15.Location = new Point(7, 0x10);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x4d, 13);
            this.label15.TabIndex = 5;
            this.label15.Text = "Start Date:";
            this.btnEPReport.Font = new Font("Verdana", 8f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btnEPReport.Location = new Point(90, 0x24);
            this.btnEPReport.Name = "btnEPReport";
            this.btnEPReport.Size = new Size(0x171, 0x21);
            this.btnEPReport.TabIndex = 0x26;
            this.btnEPReport.Text = "Generate Report";
            this.btnEPReport.UseVisualStyleBackColor = true;
            this.btnEPReport.Click += new EventHandler(this.btnEPReport_Click);
            base.AutoScaleDimensions = new SizeF(7f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.DarkBlue;
            base.ClientSize = new Size(0x30b, 0x222);
            base.ControlBox = false;
            base.Controls.Add(this.groupBox4);
            base.Controls.Add(this.label13);
            base.Controls.Add(this.btnMainMenu);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.groupBox2);
            this.Font = new Font("Verdana", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            base.MaximizeBox = false;
            this.MaximumSize = new Size(0x31b, 580);
            this.MinimumSize = new Size(0x31b, 580);
            base.Name = "importForm";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Import & Export";
            base.WindowState = FormWindowState.Maximized;
            base.Load += new EventHandler(this.importForm_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();



        }

        #endregion
    }
}